# Generated by Django 2.1.7 on 2019-09-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('companyName', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('phoneNumber', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('designation', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('companyURL', models.URLField(blank=True, default=None, null=True)),
                ('industry', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageIntroEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
