# Generated by Django 2.2 on 2020-01-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='updatePassPhrase',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
