# Generated by Django 2.2 on 2019-04-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20190217_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='companyName',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='companyURL',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='introText',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='maxBudget',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pocDesignation',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pocEmailId',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pocPhnNum',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pointOfContact',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
