# Generated by Django 2.2 on 2020-04-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200121_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rating',
            field=models.FloatField(default=None, null=True),
        ),
    ]
