# Generated by Django 2.2 on 2019-06-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_homepageintroemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='pocDesignation',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='pocPhnNum',
            new_name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='introText',
        ),
        migrations.RemoveField(
            model_name='client',
            name='maxBudget',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pocEmailId',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pointOfContact',
        ),
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
