# Generated by Django 2.1.7 on 2019-07-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20190723_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
