# Generated by Django 2.1.7 on 2019-09-22 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('influencerUsername', models.CharField(default='', max_length=50)),
                ('clientId', models.IntegerField(null=True)),
                ('message', models.TextField(null=True)),
                ('fromInfluencer', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('projectInitiationDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
