# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-17 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('responderId', models.IntegerField()),
                ('recieverId', models.IntegerField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
