# Generated by Django 2.0.6 on 2019-02-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='uid',
            field=models.BigIntegerField(),
        ),
    ]
