# Generated by Django 2.1.7 on 2019-02-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20190217_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='recieverId',
            new_name='reciverId',
        ),
    ]
