# Generated by Django 2.1.7 on 2019-05-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_auto_20190522_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='uid',
        ),
    ]
