# Generated by Django 2.1.7 on 2019-06-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_remove_messages_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='fromInfluencer',
            field=models.BooleanField(default=True),
        ),
    ]
