# Generated by Django 2.2 on 2019-06-16 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190616_0616'),
        ('conversations', '0006_messages_frominfluencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='projectInitiationDate',
            field=models.ForeignKey(default=datetime.datetime(2019, 6, 16, 6, 16, 51, 40273), on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
