# Generated by Django 2.2 on 2019-06-16 17:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_messages_projectinitiationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='projectInitiationDate',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
