# Generated by Django 2.1.7 on 2019-08-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0010_auto_20190809_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='clientId',
            field=models.IntegerField(null=True),
        ),
    ]
