# Generated by Django 2.1.7 on 2019-08-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0011_auto_20190809_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='projectInitiationDate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
