# Generated by Django 2.1.7 on 2019-09-22 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencerUsername', models.CharField(default=None, max_length=100)),
                ('clientId', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('followerCount', models.IntegerField(blank=True, default=0, null=True)),
                ('followingCount', models.IntegerField(blank=True, default=0, null=True)),
                ('dpUrl', models.URLField(blank=True, default=None, null=True)),
                ('industry', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('user', models.OneToOneField(db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
