# Generated by Django 2.2 on 2020-04-26 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencerUsername', models.CharField(default=None, max_length=100)),
                ('clientId', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('followerCount', models.IntegerField(blank=True, default=0, null=True)),
                ('followingCount', models.IntegerField(blank=True, default=0, null=True)),
                ('dpUrl', models.URLField(blank=True, default=None, null=True)),
                ('industry', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('user', models.OneToOneField(db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagramUserId', models.BigIntegerField(null=True)),
                ('influencerUserName', models.CharField(default=None, max_length=100)),
                ('accessToken', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramAuthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagramUserId', models.BigIntegerField()),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencer.Influencer')),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerPublicProfileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referralLink', models.CharField(blank=True, max_length=500, null=True)),
                ('videoLink', models.CharField(blank=True, max_length=500, null=True)),
                ('profilePicUrl', models.URLField(blank=True, default=None, null=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencer.Influencer')),
            ],
        ),
    ]
