# Generated by Django 2.0.6 on 2019-02-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencerId', models.BigIntegerField()),
                ('clientId', models.BigIntegerField()),
            ],
        ),
    ]
