# Generated by Django 2.1.7 on 2019-02-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0002_clientmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerSignUpModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='influencer',
            name='uid',
            field=models.BigIntegerField(null=True),
        ),
    ]
