# Generated by Django 2.0.6 on 2019-02-25 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('influencer', '0003_auto_20190223_0953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfluencerSignUpModel',
        ),
        migrations.AddField(
            model_name='influencer',
            name='user',
            field=models.ForeignKey(blank=True, default='0000000', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
