# Generated by Django 2.1.7 on 2019-02-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0003_auto_20190223_0953'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='InfluencerSignUpModel',
        # ),
    ]
