# Generated by Django 2.2 on 2019-10-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0003_auto_20191012_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='sourceOfOnBoard',
            field=models.CharField(default='normal', max_length=50),
        ),
        migrations.CreateModel(
            name='InstagramAuthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagramUserId', models.BigIntegerField()),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencer.Influencer')),
            ],
        ),
    ]
