# Generated by Django 2.2 on 2019-10-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0003_auto_20191012_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerpublicprofiledetails',
            name='referralLink',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='influencerpublicprofiledetails',
            name='videoLink',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
