# Generated by Django 2.2 on 2020-01-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0004_auto_20191021_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerpublicprofiledetails',
            name='referralLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='influencerpublicprofiledetails',
            name='videoLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
