# Generated by Django 2.2 on 2020-01-05 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0004_auto_20191021_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAuthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagramUserId', models.BigIntegerField()),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencer.Influencer')),
            ],
        ),
    ]
