# Generated by Django 2.2 on 2019-10-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0004_auto_20191016_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
