# Generated by Django 2.1.7 on 2019-03-02 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('influencer', '0004_delete_influencersignupmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='uid',
        ),
        migrations.AddField(
            model_name='influencer',
            name='user',
            field=models.OneToOneField(db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
