# Generated by Django 2.2 on 2020-01-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0005_instagramauthmodel'),
        ('influencer', '0005_auto_20200105_1654'),
    ]

    operations = [
    ]
