# Generated by Django 2.0.6 on 2019-03-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0005_auto_20190302_0520'),
        ('influencer', '0004_auto_20190225_1808'),
    ]

    operations = [
    ]
