# Generated by Django 2.2 on 2020-01-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0006_merge_20200106_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
