# Generated by Django 2.2 on 2019-04-19 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0006_merge_20190310_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='dpUrl',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='followerCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='followingCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='industry',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='user',
            field=models.OneToOneField(db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
