# Generated by Django 2.1.7 on 2019-03-24 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0006_merge_20190310_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='user',
            field=models.OneToOneField(db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
