# Generated by Django 2.2 on 2019-04-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0007_auto_20190419_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
