# Generated by Django 2.2 on 2020-01-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0007_auto_20200107_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
