# Generated by Django 2.2 on 2019-05-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0008_influencer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='handle',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='influencer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
