# Generated by Django 2.2 on 2020-01-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0008_auto_20200107_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerpublicprofiledetails',
            name='profilePicUrl',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
