# Generated by Django 2.2 on 2020-03-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0009_influencerpublicprofiledetails_profilepicurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagramUserId', models.BigIntegerField()),
                ('influencerUserName', models.CharField(default=None, max_length=100)),
                ('accessToken', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
