# Generated by Django 2.2 on 2019-05-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0009_auto_20190510_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='followerCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='followingCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
