# Generated by Django 2.2 on 2020-03-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0010_influenceraccesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influenceraccesstoken',
            name='instagramUserId',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
