# Generated by Django 2.1.7 on 2019-05-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0010_auto_20190511_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmapping',
            name='influencerId',
        ),
        migrations.AddField(
            model_name='clientmapping',
            name='influencerUsername',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
