# Generated by Django 2.1.7 on 2019-08-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0011_auto_20190513_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='password',
        ),
    ]
