# Generated by Django 2.2 on 2019-09-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0012_remove_influencer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
