USERNAME='username'
NEW_PASSWORD='newPassword'
COLLABERE_PASSWORD_RESET_URL='www.collabere.com/change-password/'
INFLUENCER_EMAIL='influencerEmail'
INFLUENCER_USERNAME='influencerUsername'
EMAIL_SUBJECT='PASSWORD RESET'
EMAIL_MESSAGE_STRING='Click on this link to reset password:'
SLASH="/"
INSTAGRAM="INSTAGRAM"