# Generated by Django 2.1.7 on 2019-09-22 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('minBudget', models.IntegerField(blank=True, default=None, null=True)),
                ('maxBudget', models.IntegerField(blank=True, default=None, null=True)),
                ('introText', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('projectInitiationDate', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('influencerUserName', models.CharField(max_length=50)),
                ('offeredBudget', models.IntegerField(blank=True, default=None, null=True)),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
    ]
