# Generated by Django 2.2 on 2019-06-16 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0005_auto_20190616_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('minBudget', models.IntegerField(blank=True, default=None, null=True)),
                ('maxBudget', models.IntegerField(blank=True, default=None, null=True)),
                ('introText', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('projectInitiationDate', models.DateTimeField(default=None, primary_key=True, serialize=False)),
                ('influencerUserName', models.CharField(max_length=50)),
                ('offeredBudget', models.IntegerField(blank=True, default=None, null=True)),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
    ]
