# Generated by Django 2.2 on 2020-02-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latestText',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
