# Generated by Django 2.2 on 2020-04-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_latesttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
