# Generated by Django 2.2 on 2019-06-16 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190616_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectInitiationDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 16, 6, 16, 51, 39001), primary_key=True, serialize=False),
        ),
    ]
